### DISCUSSION TITLE
Opentelemetry - what is the right configuration?

### DISCUSSION THREAD

**Discussion by vasigorc** [open-telemetry/opentelemetry-java#4298] [Q&A] [answered]
Hello 👋 

We are trying to understand what is the expected way to integrate Opentelemetry into our project for the following objective:

1. Gather traces and metrics specific to our application
2. Export them through opentelemetry-collector
3. Ingest and observe them in Elastic-Kibana stack

### Before

Previously we were able to successfully export traces only by using javaagent `1.6.0` and the following dependencies:

```scala
lazy val otelVersion = "1.6.0"
...
val compileDependencies: Seq[ModuleID] = Seq(
"io.opentelemetry" % "opentelemetry-api" % otelVersion,
"io.opentelemetry" % "opentelemetry-exporter-otlp" % otelVersion,
"io.opentelemetry" % "opentelemetry-extension-annotations" % otelVersion,
"io.opentelemetry" % "opentelemetry-sdk" % otelVersion,
"io.opentelemetry.instrumentation" % "opentelemetry-logback-1.0" % "1.4.1-alpha",
```

The way we obtained `tracer` was the following:

```scala
def getTracer: Tracer =  GlobalOpenTelemetry.getTracer(serviceName)
```

### Recently

...we set as a goal to switch on metrics through opentelemetry as well. We've updated our dependencies (including the agent) as described [here](https://github.com/open-telemetry/opentelemetry-java/issues/4297#issue-1178649479) and we set-up our `meter` using `SDKMeterProvider` as described [here](https://github.com/open-telemetry/opentelemetry-java/issues/4297#issuecomment-1076825572) 👈  in the linked comment `otel.metrics.exporter` is set to `none`, normally it was set to `otlp`. With that we were seing some metrics in opentelemetry collector, but that had severe performance impact as discussed in [this thread](https://github.com/open-telemetry/opentelemetry-java/discussions/4295).

### Lastly

As the outcome of the discussion from the last link we've removed non `opentelemetry-api` dependencies and switched to using meter derived from global scope:

```scala
def getMeter: OtelMeter = GlobalOpenTelemetry.getMeter(serviceName)
```

Unfortunately now we cannot even see our metrics in the collector at all. That seems to be in line with what the [documentation](https://opentelemetry.io/docs/concepts/instrumenting-library/#opentelemetry-api) says:

> Unless your application imports the OpenTelemetry SDK, your instrumentation does nothing and does not impact application performance.

### Issue

Together with the previous two discussions (linked in this thread) I find this confusing. I would like to understand what dependencies, versions and configurations we need to get to our objective. Do we need to rely on `GlobalOpenTelemetry` or is it considered bad? Thank you in advance for any help or relevant advice.

The collector yaml file that I use for local investigation is below.

```yaml
receivers:
  otlp/receiver:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 200
    spike_limit_mib: 100

exporters:
  otlp/elastic:
    endpoint: apm-server:8200
    tls:
      insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp/receiver]
      processors: [memory_limiter,batch]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp/receiver]
      processors: [memory_limiter,batch]
      exporters: [otlp/elastic, logging]
```

I use opentelemetry-collector version `0.46.0` and javaagent version `1.12.0`.
