### DISCUSSION TITLE
Intermittent Missing Traces

### DISCUSSION THREAD

**Discussion by sabith-nadakkavil** [open-telemetry/opentelemetry-java#7020] [Q&A] [answered]
Hi everyone,

I’ve integrated OpenObserve with my Spring Boot project and am successfully receiving traces, metrics, and logs for most of my endpoints. However, I’m facing an issue where traces appear intermittently in OpenObserve. Logs for these endpoints are consistently visible, but traces are not reliably generated or exported.

**Context:**

- My tracing configuration in application.yml is as follows:

```
management:
  otlp:
    tracing:
      export:
        enabled: true
      endpoint: ${TECHBD_OPEN_OBSERVE_URL}/api/${TECHBD_ORG_NAME}/v1/traces
      headers:
        Authorization: Basic ${TECHBD_OPEN_OBSERVE_PASSWORD}
        organization: default
        stream-name: ${TECHBD_OPEN_OBSERVE_STREAM_NAME}-traces
      sampler:
        probability: 1.0
      service:
        name: default
```

**My Questions:**

1. Are there any known scenarios where OpenObserve or the OTLP exporter might skip capturing traces sporadically?
2. Should I consider manually instrumenting these endpoints, or is there a configuration I can tweak to ensure consistency?

_Thanks in advance for any guidance!_

**Comment by cbos** [comment, marked as answer]
Hi @sabith-nadakkavil 

I think this has to do with your configuration.
This is related to Spring implementation, not the OpenTelemetry Java implemenation.

According to the documentation of Spring (https://docs.spring.io/spring-boot/reference/actuator/tracing.html):

By default, Spring Boot samples only 10% of requests to prevent overwhelming the trace backend. This property switches it to 100% so that every request is sent to the trace backend.
Configuration should look like this:
```yaml
management:
  tracing:
    sampling:
      probability: 1.0
```

So this is `management.tracing.sampling.probability`, while in your config you have set it with `management.otlp.tracing.sampler.probability`.
