### ISSUE TITLE
PrometheusExporter dropping the OTEL resource labels

### ISSUE THREAD

**Issue by yorikya** [open-telemetry/opentelemetry-java#3038]
**Describe the bug**
In our company, we are using opentelemetry-java to export the metrics from a service, then collector-agent which is running on the same host receives the metrics through the OTLP receiver and exports the metrics via the Prometheus exporter.
When we are adding some custom Lable to OTEL Resource via opentelemetry-java those Labels are dropped by Prometheus exporter, but Labels created within the metric are shown without any issue.

**Steps to reproduce**
**(Collector) Run otelcollector with the next configuration (config.yaml)**:
```
receivers:
  otlp/notls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"

  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [prometheus]
    
    traces:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [logging]   
```

**(Service) Setup opentelemetry-java to export metrics/traces via otlp (I am using this example:https://github.com/open-telemetry/opentelemetry-java/tree/main/examples/prometheus)**

Add the Resource to the PrometheusExporter:
```

public void installMetricPipeline() throws Exception {
        AttributesBuilder attributesBuilder = createAttributesBuilder();
         attributesBuilder.put(stringKey("R"), "V");
         
        meterProvider = SdkMeterProvider.builder()
            .setResource( Resource.create(attributesBuilder.build()))
            .buildAndRegisterGlobal();

        PrometheusCollector.builder().setMetricProducer(this.meterProvider).buildAndRegister();
    
        this.server = new HTTPServer(this.port);
	}
	
	 Meter meter = meterProvider.get("PrometheusExample", "0.13.1");
         meter.doubleCounterBuilder("incoming.messages").setAttributes("db_instance", "Node").build();
```

**What did you expect to see?**
Lable which is added with resources (R="V") should persist in the Prometheus tags
```
curl localhost:9090/metrics
# HELP create_node_User
# TYPE create_node_User gauge
create_node_User{db_instance="Node", R="V"} 1
```

**What did you see instead?**
The label is not showing in the Prometheus tags
```
curl localhost:9090/metrics
# HELP create_node_User
# TYPE create_node_User gauge
create_node_User{db_instance="Node"} 1
```

**What version and what artifacts are you using?**
Versions:
* [io.prometheus/simpleclient "0.10.0"]
* [io.prometheus/simpleclient_httpserver "0.10.0"]
* [io.opentelemetry/opentelemetry-exporter-prometheus "1.0.0-alpha"]
* [io.opentelemetry/opentelemetry-sdk "1.0.0"]
* [io.opentelemetry/opentelemetry-api "1.0.0"]

**Environment**
Java: 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-macosx) (build 1.8.0_252-b14)
OS:
Ubuntu14
MacOS: 11.2.3

**Additional context**
I have the same issue with opentelemetry-go
https://github.com/open-telemetry/opentelemetry-collector/issues/2498
