### ISSUE TITLE
Registering multiple asynchronous instruments

### ISSUE THREAD

**Issue by fabianishere** [open-telemetry/opentelemetry-java#3549]
**Describe the bug**
I have been experimenting with the latest OpenTelemetry Metrics release (version 1.5.0-alpha), but it has occurred to me that registering multiple asynchronous instruments with the same name will result in only one of the callbacks being invoked during a collection cycle.

I want to implement a pattern like this:
```kotlin
public class Host(public val uid: UUID, meter: Meter, ....) {
    init {
        meter.gaugeBuilder("cpu.usage")
            .setDescription("The amount of CPU resources used by the host")
            .setUnit("MHz")
            .buildWithCallback { result ->
                val cpuUsage = ...
                result.observe(cpuUsage, Attributes.of(ResourceAttributes.HOST_ID, uid.toString()))
            }
    }
}
```

**Steps to reproduce**
1. Create multiple asynchronous instruments with the same name
2. Observe that only one callback is invoked during the collection cycle

**What did you expect to see?**
Every asynchronous instrument with the same should have its callback invoked every collection cycle.

**What did you see instead?**
Only one of the asynchronous instrument callbacks is invoked every collection cycle.

**What version and what artifacts are you using?**
This is the Gradle version catalog I use for the OpenTelemetry artifacts:
```toml
[versions]
opentelemetry-main = "1.5.0"
opentelemetry-metrics = "1.5.0-alpha"
opentelemetry-semconv = "1.5.0-alpha"

[libraries]
opentelemetry-api-main = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry-main" }
opentelemetry-sdk-main = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry-main" }
opentelemetry-api-metrics = { module = "io.opentelemetry:opentelemetry-api-metrics", version.ref = "opentelemetry-metrics" }
opentelemetry-sdk-metrics = { module = "io.opentelemetry:opentelemetry-sdk-metrics", version.ref = "opentelemetry-metrics" }
opentelemetry-semconv = { module = "io.opentelemetry:opentelemetry-semconv", version.ref = "opentelemetry-semconv" }
```

**Environment**
Compiler: Oracle JDK 16.0.2
OS: macOS Big Sur
