### ISSUE TITLE
Properties of sampler can not be transformed to  YAML

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java#3940]
![image](https://user-images.githubusercontent.com/11512994/144014843-f4f3c050-043f-4c70-85dd-5c810da3c0a6.png)
The [System property]( https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler) names is nested,can not be transformed to  YAML . If we want to read from yaml file in the future versions,it will be a bug.

I think it should be added a `name` to the Properties,like this:
```
otel.traces.sampler.name
otel.traces.sampler.arg
```
Then it will be transformed:
```
otel:
   traces:
     exporter: otlp  
     sampler:
       name: parentbased_always_on
       arg:
```
