### ISSUE TITLE
View file based configuration for histogram bucket boundaries

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4586]
The [view file based configuration](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/metric-incubator#view-file-configuration) should support configuring explicit bucket histogram bucket boundaries, as well as the number of buckets for exponential histograms. 

Configuring explicit bucket bounds may look like:
```
- selector:
    instrument_type: HISTOGRAM
  view:
    aggregation: explicit_bucket_histogram
    aggregation_args:
        bucket_boundaries: [5.0, 10.0, 100.0]
```

Configuring exponential bucket count may look like:
```
- selector:
    instrument_type: HISTOGRAM
  view:
    aggregation: exponential_histogram
    aggregation_args:
        max_buckets: 20
```
