### ISSUE TITLE
First trace data will be partially lost after collector restart

### ISSUE THREAD

**Issue by tuhao1020** [open-telemetry/opentelemetry-java#5441]
In k8s environment, restart the collector and wait for the collector to be ready, the trace data generated by the first access to the service will be partially lost(sampler = 100%), the following errors will appear in the service's logs:
```
ERROR io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export spans. the request could not be executed. full error message. Failed to connect to otel-collector/10.1.0.192:14317
```

collector config:
```
extensions:
  health_check: {}
receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: :14317
processors:
  batch: {}        
exporters:
  otlp:
    endpoint: http://jaeger-prod-collector.istio-system:4317  # to jaeger
    tls:
      insecure: true
service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [logging, otlp]
```
I have set OTEL_EXPERIMENTAL_EXPORTER_OTLP_RETRY_ENABLED to true, but not worked

trace data I got (4 spans):
<img width="461" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/26807520/a54fa436-3322-4935-b73f-bad8387d54be">

expected (6 spans):
<img width="732" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/26807520/cafc8b2b-1970-4a6a-99d4-0b8a25561157">

#4279  this issue does not solve my problem either
