### ISSUE TITLE
Application logs are not exported to elastic backend by otel collector deployed as side car in minikube

### ISSUE THREAD

**Issue by MadhusudanN** [open-telemetry/opentelemetry-java#5752]
**Describe the bug**
Logs of the application are not getting exported to the elastic backend even though the otlp receiver to receive logs from instrumentation library is enabled and elastic exporter configurations are enabled.  I am able to see traces and metrics are exported to elastic but not logs.

Please find below the collector configuration as a sidecar.
```sh
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-collector
spec:
  mode: sidecar
  config: >
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
      hostmetrics/disk:
        collection_interval: 1m
        scrapers:
          disk:
          filesystem:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:
    exporters:
      logging:
      otlp/elastic:
        endpoint: "2ec0110ca80e4e159f4e20d227da8f0b.apm.us-central1.gcp.cloud.es.io:443"
        compression: none
        headers:
          Authorization: "Bearer <TOKEN>"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging, otlp/elastic]
        metrics:
          receivers: [otlp, hostmetrics, hostmetrics/disk]
          exporters: [logging, otlp/elastic]
        logs:
          receivers: [otlp]
          exporters: [logging, otlp/elastic]
EOF
```

Please find the instrumentation resource configuration below.

```sh
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://localhost:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://localhost:4318
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://localhost:4317
EOF
```

The application deployment file looks like below ::
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-department-service
  labels:
    app: rolldice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-department-service
  template:
    metadata:
      labels:
        app: auto-department-service
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
      - name: auto-department-service
        image: xxxx/auto-department-service:latest
        ports:
        - containerPort: 8085
      imagePullSecrets:
      - name: xxxx
```

I did enable debug logs of collector along with debug logs of instrumentation injected into the app, but could not find any issues reporting failure to collect logs or failure to publish. PFA the logs with this bug.

**Steps to reproduce**
Using the above configurations, the app is brought up we see traces and metrics in elastic backend but not the logs associated with the traces.

**What did you expect to see?**
We would expect that app logs are also instrumented, collected and published to elastic backend

**What did you see instead?**
Logs are not appearing in the elastic search backend, only traces and metrics are observed.

**What version and what artifacts are you using?**
Artifacts: (e.g., `opentelemetry-api`, `opentelemetry-sdk`, which exporters, etc)
minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b

open telemetry operator version :: 1.26.0

open telemetry collector version :: 0.81.0

OS :: 
RHEL 7.9 GA

For app,A fat jar is created and is containerized in a docker. This image is maintained in a local repo. This image is used to deploy the app

Additional Details ::
 The same app when deployed in no collector mode (by directly plugging the instrumentation jar) I am able to see the logs getting published.
The below configurations are used to start the app.

```
-Dotel.exporter.otlp.headers="Authorization=Bearer <Token>" -Dotel.exporter.otlp.endpoint=https://2ec0110ca80e4e159f4e20d227da8f0b.apm.us-central1.gcp.cloud.es.io:443 -Dotel.service.name=departmentSvc -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.logs.exporter=otlp -javaagent:C:\Open_Telemetry\opentelemetry-javaagent.jar  -Dotel.javaagent.debug=true
```

Can you please look into this and help with further debugging on this.
