### ISSUE TITLE
ConfigurationFactory requires '{}' for keys when no configuration is present

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#5828]
Suppose you want to configure the console exporter using file configuration. You might have a configuration like:
```
tracer_provider:
  processors:
    - batch:
         exporter:
           console:
```
But this wont work. For the reason described [here](https://github.com/open-telemetry/opentelemetry-java-examples/pull/207#discussion_r1324642412), you need to configure console with an empty object `{}`:
```
tracer_provider:
  processors:
    - batch:
         exporter:
           console: {}
```
This is inconvenient, error prone, and surprising. Investigate jackson configuration options to see if we can remove this requirement.
