### ISSUE TITLE
Failed to export metrics. Server responded with gRPC status code 2

### ISSUE THREAD

**Issue by IamSatyaonline** [open-telemetry/opentelemetry-java#5974]
**Describe the bug**
We have deployed an java application with javaAgent auto instrumentation, We are getting an error that 'failed to export metrics' as below
```
otel.javaagent 2023-11-10 07:25:35:558 +0000] [OkHttp http://otel-collector:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with UNIMPLEMENTED. This usually means that your collector is not configured with an otlp receiver in the "pipelines" section of the configuration. If export is not desired and you are using OpenTelemetry autoconfiguration or the javaagent, disable export by setting OTEL_METRICS_EXPORTER=none. Full error message: unknown service opentelemetry.proto.collector.metrics.v1.MetricsService
[otel.javaagent 2023-11-10 07:38:36:552 +0000] [OkHttp http://otel-collector:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to otel-collector/10.109.143.240:4317
[otel.javaagent 2023-11-10 07:39:36:543 +0000] [OkHttp http://otel-collector:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to otel-collector/10.109.143.240:4317
[otel.javaagent 2023-11-10 07:40:36:539 +0000] [OkHttp http://otel-collector:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to otel-collector/10.109.143.240:4317
```

**Steps to reproduce**
1. Create instrumentation
2. deploy the apps with deployment object
3. Create opentelemetry collection using yaml file.

**What did you expect to see?**
We should be able to get the metrics.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version and what artifacts are you using?**
Artifacts: javaAgent: 1.31.0, operator=0.88.0 

How did you reference these artifacts? ( `pom.xml`)

**Environment**
Compiler: (e.g., "java 17")
OS: (e.g., "Linux")

**Additional context**
```
Instrumentation:

kubectl -n cert-manager apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
EOF

Deployment-app:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: app
        image: ghcr.io/pavolloffay/spring-petclinic:latest
	
	
Opentelemetry Collector:

kubectl -n cert-manager apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
EOF

```
