### ISSUE TITLE
 ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs inside docker

### ISSUE THREAD

**Issue by kgoedert** [open-telemetry/opentelemetry-java#6467]
**Describe the bug**
If I run the application outside the docker container, I am able to export logs and metrics. But if I run it inside a docker container, it fails do connect to localhost. I would like to know, which property I should configure in spring boot application.yml

this is my application-hml.yml
```
spring.application.name=cart-api
spring.datasource.url=jdbc:otel:mysql://192.168.15.18:3306/cart
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver

server.servlet.context-path=/cart/api

otel.sdk.disabled=false
management.endpoints.web.exposure.include=health
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
management.otlp.metrics.export.step=10s
management.server.port=8082
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces
# sampling every request
management.tracing.sampling.probability=1.0   
otel.service.name=cart-api
otel.exporter.otlp.logs.endpoint=http://otel-collector:4318/v1/logs
otel.exporter.otlp.endpoint=http://otel-collector:4318
```

this is my docker-compose:

```
version: '3.4'
networks:
  cart:
    driver: bridge

services:
  app:
    build: app
    networks:
      - cart
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - tempo
      - otel-collector
      - loki
      - grafana
      - prometheus
    privileged: true

  otel-collector:
    build: otel-collector
    networks:
      - cart
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otelcol-contrib/otel-collector.yml
```

this is the Dockerfile of the application:

```
FROM eclipse-temurin:21-jre

ENV PYROSCOPE_APPLICATION_NAME=simple.java.app
ENV PYROSCOPE_PROFILING_INTERVAL=10ms
ENV PYROSCOPE_PROFILER_EVENT=itimer
ENV PYROSCOPE_PROFILER_LOCK=10ms
ENV PYROSCOPE_PROFILER_ALLOC=512k
ENV PYROSCOPE_UPLOAD_INTERVAL=15s
ENV PYROSCOPE_LOG_LEVEL=debug
ENV PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040


ADD https://github.com/grafana/pyroscope-java/releases/download/v0.13.1/pyroscope.jar /pyroscope.jar
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.4.0/opentelemetry-javaagent.jar /opentelemetry-javaagent.jar

ADD cart-api-0.0.4-SNAPSHOT.jar /app.jar

EXPOSE 8080
EXPOSE 8282

CMD ["java", "-XX:-Inline", "-javaagent:pyroscope.jar", "-javaagent:opentelemetry-javaagent.jar", "-Dspring.profiles.active=hml", "-jar" ,"/app.jar"]
```

and this is the log message in the application when running inside the docker container

```
[otel.javaagent 2024-05-20 19:13:48:658 +0000] [OkHttp http://localhost:4318/...] ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4318
app_1             | java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4318
app_1             | 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
app_1             | 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
app_1             | 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
app_1             | 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
app_1             | 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
app_1             | 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
app_1             | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
app_1             | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
app_1             | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
app_1             | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
app_1             | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
app_1             | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
app_1             | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
app_1             | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
app_1             | 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
app_1             | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
app_1             | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
app_1             | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
app_1             | 	at java.base/java.lang.Thread.run(Unknown Source)
app_1             | Caused by: java.net.ConnectException: Connection refused
app_1             | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
app_1             | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
app_1             | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
app_1             | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
app_1             | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
app_1             | 	at java.base/java.net.Socket.connect(Unknown Source)
app_1             | 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
app_1             | 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)

```

Which property should I configure so I can connect to the otel-collector?
