### ISSUE TITLE
OkHttp sender exports traces of it exporting traces

### ISSUE THREAD

**Issue by gravieure** [open-telemetry/opentelemetry-java#6723]
**Describe the bug**

I have a Kotlin/ktor project running as an AWS Fargate task, exporting traces via gRPC to a Datadog agent, using the default `OkHttp` sender.  I'm using autoconfiguration.

I'm seeing a high volume of traces which appear to be caused by OkHttp being instrumented to record traces, and also used to export those same traces.  The volume is approximately one trace every five seconds.  Example trace:

```json
{
    "component": "okhttp",
    "http": {
        "host": "localhost",
        "method": "POST",
        "path_group": "/?/Export",
        "status_code": "200",
        "url": "http://localhost:4317/opentelemetry.proto.collector.trace.v1.TraceService/Export",
        "url_details": {
            "host": "localhost",
            "path": "/opentelemetry.proto.collector.trace.v1.TraceService/Export",
            "port": "4317",
            "scheme": "http"
        }
    },
    "language": "jvm",
    "peer": {
        "hostname": "localhost",
        "port": 4317
    },
    "process_id": "13",
    "runtime-id": "22af4f8c-96df-4a33-96ae-06a1b3a594ba",
    "span": {
        "kind": "client"
    },
    "thread": {
        "id": 50,
        "name": "OkHttp http://localhost:4317/..."
    },
    "version": "1.0.21"
}
```

I'm not sure if this is due to how I have this application instrumented/configured, or a bug.

**Steps to reproduce**

Use autoconfiguration to trace a JVM application, exporting traces to an OTEL agent over gRPC with the default OkHttp sender.

**What did you expect to see?**

Traces from my application only.

**What did you see instead?**

Traces from my application and opentelemetry exporting those same traces.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-ktor-2.0, opentelemetry-sdk-extension-autoconfigure, opentelemetry-exporter-otlp, 
Version: 1.41.0 for main otel deps, 2.7.0-alpha for ktor-2.0.
How did you reference these artifacts?

`gradle/libs.versions.toml`
```toml
[versions]
opentelemetry-version-alpha = "2.7.0-alpha"
opentelemetry-version = "1.41.0"

[libraries]
opentelemetry-ktor = { module = "io.opentelemetry.instrumentation:opentelemetry-ktor-2.0", version.ref = "opentelemetry-version-alpha" }
opentelemetry-sdk-extension-autoconfigure = { module = "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure", version.ref = "opentelemetry-version"}
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry-version"}
```

`build.gradle.kts`:
```kotlin
dependencies {
    // OpenTelemetry
    implementation(libs.opentelemetry.ktor)
    implementation(libs.opentelemetry.sdk.extension.autoconfigure)
    implementation(libs.opentelemetry.exporter.otlp)
}
```

**Environment**
Compiler: Amazon Coretto 21
OS: Amazon Linux 2023.
Runtime (if different from JDK above): Same
OS (if different from OS compiled on): Same

**Additional context**

I have no explicit environment or property configurations for otel.

I'm using the Datadog agent with OTEL enabled (`-javaagent:/path/to/dd-java-agent.jar`).

I'm *not* using the OpenTelemetry Java agent.
